version: '3.3'

services:
  app:
    build: .
    ports:
      - "8501:8501"     # Streamlit UI
      - "5000:5000"     # Flask API
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/klimmzug_timer
    volumes:
      - ./logs:/app/logs  # Optional: Log directory

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
